from project.constants import *

ARTICLE_STATUS_WAITING = 0
ARTICLE_STATUS_PUBLISHED = 1
ARTICLE_STATUS_REJECTED = 2
ARTICLE_STATUS_CHOICE = Choices(
    (ARTICLE_STATUS_WAITING, '待审核'),
    (ARTICLE_STATUS_PUBLISHED, '已发布'),
    (ARTICLE_STATUS_REJECTED, '禁用/拒绝')
)
