from project.constants import *

PRICE_TYPE_FIXED = 0
PRICE_TYPE_CHOICE = Choices(
    (PRICE_TYPE_FIXED, '固定价格')
)

# 订单状态
ORDER_STATUS_WAITING_CONFIRM = -1
ORDER_STATUS_WAITING = 0
ORDER_STATUS_SERVICING = 1
ORDER_STATUS_FINISHED = 2
ORDER_STATUS_CANCEL = 3
ORDER_STATUS_EVALUATE = 4
ORDER_STATUS_WAITING_PAY = 5
ORDER_STATUS_CHOICE = Choices(
    (ORDER_STATUS_WAITING_CONFIRM, '待接单'),
    (ORDER_STATUS_WAITING, '待服务'),
    (ORDER_STATUS_SERVICING, '服务中'),
    (ORDER_STATUS_FINISHED, '已完成'),
    (ORDER_STATUS_CANCEL, '已取消'),
    (ORDER_STATUS_EVALUATE, '已评价'),
    (ORDER_STATUS_WAITING_PAY, '待支付')
)

# 取消类型
CANCEL_TYPE_USER = 0
CANCEL_TYPE_BARBER = 1
CANCEL_TYPE_TIMEOUT = 2
CANCEL_TYPE_CHOICE = Choices(
    (CANCEL_TYPE_USER, '用户取消'),
    (CANCEL_TYPE_BARBER, '理发师取消'),
    (CANCEL_TYPE_TIMEOUT, '超时取消')
)

# 订单类型
ORDER_TYPE_FORTHWITH = 0
ORDER_TYPE_BOOKING = 1
ORDER_TYPE_CHOICE = Choices(
    (ORDER_TYPE_FORTHWITH, '即时取号'),
    (ORDER_TYPE_BOOKING, '预约取号')
)

# 支付类型
ORDER_PAY_TYPE_NET = 0
ORDER_PAY_TYPE_REALITY = 1
ORDER_PAY_TYPE_CHOICES = Choices(
    (ORDER_PAY_TYPE_NET, '线上支付'),
    (ORDER_PAY_TYPE_REALITY, '线下支付')
)

# 付款金额类型
ORDER_PAY_AMOUNT_TYPE_REALITY = 0
ORDER_PAY_AMOUNT_TYPE_WECHAT = 1
ORDER_PAY_AMOUNT_TYPE_BALANCE = 2
ORDER_PAY_AMOUNT_TYPE_BALANCE_AND_WECHAT = 3
ORDER_PAY_AMOUNT_TYPE_CHOICES = Choices(
    (ORDER_PAY_AMOUNT_TYPE_REALITY, '现金支付'),
    (ORDER_PAY_AMOUNT_TYPE_WECHAT, '微信支付'),
    (ORDER_PAY_AMOUNT_TYPE_BALANCE, '余额支付'),
    (ORDER_PAY_AMOUNT_TYPE_BALANCE_AND_WECHAT, '余额支付+微信支付')
)

# 支付模式
PAY_PATTERN_COMMON = 0
PAY_PATTERN_DIRECT = 1
PAY_PATTERN_CHOICES = Choices(
    PAY_PATTERN_COMMON, '普通支付',
    PAY_PATTERN_DIRECT, '提前支付'
)

# 支付状态
PAY_STATUS_NO = 0
PAY_STATUS_SUCCESS = 1
PAY_STATUS_CHOICES = Choices(
    (PAY_STATUS_NO, '未支付'),
    (PAY_STATUS_SUCCESS, '已支付')
)

# 退款状态
REFUND_STATUS_NO = 0
REFUND_STATUS_SUCCESS = 1
REFUND_STATUS_FAIL = 2
REFUND_STATUS_CHOICES = Choices(
    (REFUND_STATUS_NO, '未退款'),
    (REFUND_STATUS_SUCCESS, '退款成功'),
    (REFUND_STATUS_FAIL, '退款失败')
)

# 服务费状态
SERVICE_FEE_STATUS_NO = 0
SERVICE_FEE_STATUS_SUCCESS = 1
SERVICE_FEE_STATUS_CHOICES = Choices(
    (SERVICE_FEE_STATUS_NO, '未收取'),
    (SERVICE_FEE_STATUS_SUCCESS, '已收取')
)
