from project.constants import *

DAY_MONDAY = 1
DAY_TUESDAY = 2
DAY_WEDNESDAY = 3
DAY_THURSDAY = 4
DAY_FRIDAY = 5
DAY_SATURDAY = 6
DAY_SUNDAY = 7
DAY_CHOICE = Choices(
    (DAY_MONDAY, '周一'),
    (DAY_TUESDAY, '周二'),
    (DAY_WEDNESDAY, '周三'),
    (DAY_THURSDAY, '周四'),
    (DAY_FRIDAY, '周五'),
    (DAY_SATURDAY, '周六'),
    (DAY_SUNDAY, '周日')
)

SHOP_STATUS_NOT = 0
SHOP_STATUS_ENABLED = 1
SHOP_STATUS_DISABLED = 2
SHOP_STATUS_APPROVE = 3
SHOP_STATUS_CHOICE = Choices(
    (SHOP_STATUS_NOT, '未审核'),
    (SHOP_STATUS_ENABLED, '有效'),
    (SHOP_STATUS_DISABLED, '禁用'),
    (SHOP_STATUS_APPROVE, '拒绝审核')
)

SHOP_BUSINESS_STATUS_CLOSED = 0
SHOP_BUSINESS_STATUS_OPENING = 1
SHOP_BUSINESS_STATUS_CHOICES = Choices(
    (SHOP_BUSINESS_STATUS_CLOSED, '打烊'),
    (SHOP_BUSINESS_STATUS_OPENING, '营业中'),
)

ERROR_SHOP_LOG_EXIST = 4001  # 店铺不存在

# 店铺取号类型
SHOP_BOOKING_TYPE_FORTHWITH = 0
SHOP_BOOKING_TYPE_BOOK = 1
SHOP_BOOKING_TYPE_ALL = 2
SHOP_BOOKING_TYPE_CHOICES = Choices(
    (SHOP_BOOKING_TYPE_FORTHWITH, '即时取号'),
    (SHOP_BOOKING_TYPE_BOOK, '预约取号'),
    (SHOP_BOOKING_TYPE_ALL, '即时取号+预约取号')
)

# 商户进件状态
PAY_APPLY_STATUS_APPLYING = 0
PAY_APPLY_STATUS_SUCCESS = 1
PAY_APPLY_STATUS_REJECT = 2
PAY_APPLY_STATUS_CANCEL = 3
PAY_APPLY_STATUS_WAITING_SIGNED = 4
PAY_APPLY_STATUS_CHOICES = Choices(
    (PAY_APPLY_STATUS_APPLYING, '申请中'),
    (PAY_APPLY_STATUS_SUCCESS, '申请成功'),
    (PAY_APPLY_STATUS_REJECT, '已驳回'),
    (PAY_APPLY_STATUS_CANCEL, '已撤销'),
    (PAY_APPLY_STATUS_WAITING_SIGNED, '待签约')
)

# 支付服务开通状态
SHOP_PAY_SERVICE_STATUS_NOT = 0
SHOP_PAY_SERVICE_STATUS_APPLYING = 1
SHOP_PAY_SERVICE_STATUS_SUCCESS = 2
SHOP_PAY_SERVICE_STATUS_FAIL = 3
SHOP_PAY_SERVICE_STATUS_WAITING_SIGNED = 4
SHOP_PAY_SERVICE_STATUS_CHOICES = Choices(
    (SHOP_PAY_SERVICE_STATUS_NOT, '未开通'),
    (SHOP_PAY_SERVICE_STATUS_APPLYING, '审核中'),
    (SHOP_PAY_SERVICE_STATUS_SUCCESS, '开通成功'),
    (SHOP_PAY_SERVICE_STATUS_FAIL, '开通失败'),
    (SHOP_PAY_SERVICE_STATUS_WAITING_SIGNED, '待签约')
)
# 证件有效期类型
ID_CARD_VALID_TYPE_FIXED_DATE = 0
ID_CARD_VALID_TYPE_LONG_DATE = 1
ID_CARD_VALID_TYPE_CHOICES = Choices(
    (ID_CARD_VALID_TYPE_FIXED_DATE, '定期'),
    (ID_CARD_VALID_TYPE_LONG_DATE, '长期')
)

# 项目价格是否保密
SERVICE_PRICE_SECRECY_NO = 0
SERVICE_PRICE_SECRECY_YES = 1
SERVICE_PRICE_SECRECY_TABLE = Choices(
    (SERVICE_PRICE_SECRECY_NO, '价格不保密'),
    (SERVICE_PRICE_SECRECY_YES, '价格保密')
)

# 店铺版本
SHOP_VERSION_FREE = 0
SHOP_VERSION_HIGH = 1
SHOP_VERSION_CHOICES = Choices(
    (SHOP_VERSION_FREE, '免费版'),
    (SHOP_VERSION_HIGH, '高级版')
)

# 订单状态
ORDER_STATUS_WAITING_PAY = 0
ORDER_STATUS_SUCCESS_PAY = 1
ORDER_STATUS_CANCEL = 2
ORDER_STATUS_CHOICE = Choices(
    (ORDER_STATUS_WAITING_PAY, '待支付'),
    (ORDER_STATUS_SUCCESS_PAY, '已支付'),
    (ORDER_STATUS_CANCEL, '已取消')
)

# 店铺版本过期类型
SHOP_EXPIRE_TYPE_ALWAYS = 0
SHOP_EXPIRE_TYPE_ONE_YEAR = 1
SHOP_EXPIRE_TYPE_CHOICES = Choices(
    (SHOP_EXPIRE_TYPE_ALWAYS, '永久'),
    (SHOP_EXPIRE_TYPE_ONE_YEAR, '一年')
)

# 店铺营业类型
SHOP_BUSINESS_TYPE_REAL = 0
SHOP_BUSINESS_TYPE_VIRTUAL = 1
SHOP_BUSINESS_TYPE_CHOICES = Choices(
    (SHOP_BUSINESS_TYPE_REAL, '门店经营'),
    (SHOP_BUSINESS_TYPE_VIRTUAL, '上门服务')
)
