from project.constants import *
FEEDBACK_STATUS_WAITING = 0
FEEDBACK_STATUS_REPLIED = 1
FEEDBACK_STATUS_FINISH = 2
FEEDBACK_STATUS_CHOICE = Choices(
    (FEEDBACK_STATUS_WAITING, '待处理'),
    (FEEDBACK_STATUS_REPLIED, '已回复'),
    (FEEDBACK_STATUS_FINISH, '已结束'),
)

FEEDBACK_TYPE_ADVICE = 0
FEEDBACK_TYPE_COMPLAIN = 1
FEEDBACK_TYPE_COMMON = 2
FEEDBACK_TYPE_HELP = Choices(
    (FEEDBACK_TYPE_ADVICE, '咨询'),
    (FEEDBACK_TYPE_COMPLAIN, '投诉'),
    (FEEDBACK_TYPE_COMMON, '常见问题'),
)

FEEDBACK_RANK_USEFUL = 0
FEEDBACK_RANK_USELESS = 1
FEEDBACK_RANK_CHOICE = Choices(
    (FEEDBACK_RANK_USEFUL, '有用'),
    (FEEDBACK_RANK_USELESS, '没用'),
)

FEEDBACK_COMMENT_USER_TYPE_CUSTOMER = 0
FEEDBACK_COMMENT_USER_TYPE_SERVER = 1

FEEDBACK_COMMENT_USER_TYPE_CHOICE = Choices(
    (FEEDBACK_COMMENT_USER_TYPE_CUSTOMER, '用户'),
    (FEEDBACK_COMMENT_USER_TYPE_SERVER, '客服')
)

BANNER_APPLET_TYPE_MERCHANT = 0
BANNER_APPLET_TYPE_CUSTOMER = 1
BANNER_APPLET_TYPE_CHOICE = Choices(
    (BANNER_APPLET_TYPE_MERCHANT, '商户小程序'),
    (BANNER_APPLET_TYPE_CUSTOMER, '消费者小程序')
)