from project.constants import *

# 会员卡折扣类型
CARD_DISCOUNT_TYPE_DISCOUNT = 0
CARD_DISCOUNT_TYPE_REDUCTION = 1
CARD_DISCOUNT_TYPE_CHOICES = Choices(
    (CARD_DISCOUNT_TYPE_DISCOUNT, '每单折扣'),
    (CARD_DISCOUNT_TYPE_REDUCTION, '每单立减')
)

# 会员卡等级
CARD_LEVEL_FIRST = 0
CARD_LEVEL_SECOND = 1
CARD_LEVEL_THIRD = 2
CARD_LEVEL_FOURTH = 3
CARD_LEVEL_CHOICES = Choices(
    (CARD_LEVEL_FIRST, '钻石VIP'),
    (CARD_LEVEL_SECOND, '黑金VIP'),
    (CARD_LEVEL_THIRD, '铂金VIP'),
    (CARD_LEVEL_FOURTH, '白金VIP')
)

# 会员卡过期类型
CARD_EXPIRE_TYPE_ALWAYS = 0
CARD_EXPIRE_TYPE_YEAR = 1
CARD_EXPIRE_TYPE_CHOICES = Choices(
    (CARD_EXPIRE_TYPE_ALWAYS, '永久'),
    (CARD_EXPIRE_TYPE_YEAR, '一年')
)

# 用户会员卡状态
CARD_STATUS_NORMAL = 0
CARD_STATUS_DISABLED = 1
CARD_STATUS_EXPIRE = 2
CARD_STATUS_CHOICES = Choices(
    (CARD_STATUS_NORMAL, '正常'),
    (CARD_STATUS_DISABLED, '禁用'),
    (CARD_STATUS_EXPIRE, '已过期')
)

# 服务费状态
SERVICE_FEE_STATUS_NO = 0
SERVICE_FEE_STATUS_SUCCESS = 1
SERVICE_FEE_STATUS_CHOICES = Choices(
    (SERVICE_FEE_STATUS_NO, '未收取'),
    (SERVICE_FEE_STATUS_SUCCESS, '已收取')
)

# 订单状态
ORDER_STATUS_WAITING_PAY = 0
ORDER_STATUS_SUCCESS_PAY = 1
ORDER_STATUS_CANCEL = 2
ORDER_STATUS_CHOICE = Choices(
    (ORDER_STATUS_WAITING_PAY, '待支付'),
    (ORDER_STATUS_SUCCESS_PAY, '已支付'),
    (ORDER_STATUS_CANCEL, '已取消')
)
