from project.constants import *

MENU_MODE_IFRAME = 0
MENU_MODE_EXPAND = 1

MENU_MODE_CHOICE = Choices(
    (MENU_MODE_IFRAME, 'iframe', 'iframe'),
    (MENU_MODE_EXPAND, 'expand', 'expand')
)

GENDER_TYPE_UNKNOWN = 0
GENDER_TYPE_MALE = 1
GENDER_TYPE_FEMALE = 2

GENDER_CHOICE = Choices(
    (GENDER_TYPE_UNKNOWN, 'unknown', '未知'),
    (GENDER_TYPE_MALE, 'male', '男'),
    (GENDER_TYPE_FEMALE, 'female', '女'),
)

AUTHORIZE_OBJECT_TYPE_USER = 0
AUTHORIZE_OBJECT_TYPE_ROLE = 1

AUTHORIZE_OBJECT_TYPE_CHOICE = Choices(
    (AUTHORIZE_OBJECT_TYPE_USER, 'user', '用户'),
    (AUTHORIZE_OBJECT_TYPE_ROLE, 'role', '角色'),
)
AUTHORIZE_ITEM_TYPE_MODULE = 0
AUTHORIZE_ITEM_TYPE_BUTTON = 1
AUTHORIZE_ITEM_TYPE_VIEW = 2
AUTHORIZE_ITEM_TYPE_FORM = 3

AUTHORIZE_ITEM_TYPE_CHOICE = Choices(
    (AUTHORIZE_ITEM_TYPE_MODULE, 'module', '模块'),
    (AUTHORIZE_ITEM_TYPE_BUTTON, 'button', '按钮'),
    (AUTHORIZE_ITEM_TYPE_VIEW, 'view', '视图'),
    (AUTHORIZE_ITEM_TYPE_FORM, 'form', '表单'),
)

LOG_TYPE_UNKNOWN = 0
LOG_TYPE_LOGIN = 1
LOG_TYPE_VIEW = 2
LOG_TYPE_ACTION = 3
LOG_TYPE_EXCEPTION = 4
LOG_TYPE_CHOICE = Choices(
    (LOG_TYPE_LOGIN, '未知'),
    (LOG_TYPE_LOGIN, '登陆'),
    (LOG_TYPE_VIEW, '访问'),
    (LOG_TYPE_ACTION, '操作'),
    (LOG_TYPE_EXCEPTION, '异常')
)

LOG_RESULT_SUCCESS = 0
LOG_RESULT_FAILED = 1
LOG_RESULT_CHOICE = Choices(
    (LOG_RESULT_SUCCESS, '成功'),
    (LOG_RESULT_FAILED, '失败')
)

# =================
# ERROR TABLE
# =================

ERROR_PHONE_UNREGISTERED = 2001  # 未注册
ERROR_PHONE_REGISTERED = 2002  # 已注册
ERROR_ACCOUNT_MOBILE_ERROR = 2003  # 电话号码错误
ERROR_ACCOUNT_PASSWORD_ERROR = 2004  # 密码错误
ERROR_ACCOUNT_DISABLED = 2005  # 账号已禁用

ERROR_CHOICE = Choices(
    (ERROR_PHONE_UNREGISTERED, '未注册'),
    (ERROR_PHONE_REGISTERED, '账号已注册'),
    (ERROR_ACCOUNT_MOBILE_ERROR, '电话号码错误'),
    (ERROR_ACCOUNT_PASSWORD_ERROR, '密码错误'),
    (ERROR_ACCOUNT_DISABLED, '账号已禁用')
)

LOG_MODULE_NMAE = "POS超级码牌系统管理后台"
