from project.constants import *


COUPON_TYPE_CASH = 0
COUPON_TYPE_FULL_REDUCTION = 1
COUPON_TYPE_DISCOUNT = 2

COUPON_TYPE_CHOICE = Choices(
    (COUPON_TYPE_CASH, '代金券(无门槛)'),
    (COUPON_TYPE_FULL_REDUCTION, '满减券'),
    (COUPON_TYPE_DISCOUNT, '折扣券')
)

COUPON_VALUE_TYPE_FIXED = 0
COUPON_VALUE_TYPE_FLOAT = 1
COUPON_VALUE_TYPE_CHOICE = Choices(
    (COUPON_VALUE_TYPE_FIXED, '固定金额'),
    (COUPON_VALUE_TYPE_FLOAT, '浮动金额')
)

COUPON_VALIDITY_TYPE_FIXED = 0
COUPON_VALIDITY_TYPE_DAYS = 1
COUPON_VALIDITY_TYPE_CHOICE = Choices(
    (COUPON_VALIDITY_TYPE_FIXED, '固定有效期'),
    (COUPON_VALIDITY_TYPE_DAYS, '浮动有效期')
)

VOUCHER_STATUS_WAITING = 0
VOUCHER_STATUS_USED = 1
VOUCHER_STATUS_EXPIRED = 2
VOUCHER_STATUS_CHOICE = Choices(
    (VOUCHER_STATUS_WAITING, '待核销'),
    (VOUCHER_STATUS_USED, '已核销'),
    (VOUCHER_STATUS_EXPIRED, '已过期')
)

