from project.constants import *

BANNER_JUMP_TYPE_APPLET = 0
BANNER_JUMP_TYPE_URL = 1
BANNER_JUMP_TYPE_OTHER_APPLET = 2

BANNER_JUMP_TYPE_CHOICE = Choices(
    (BANNER_JUMP_TYPE_APPLET, '当前小程序页面'),
    (BANNER_JUMP_TYPE_URL, '网址链接'),
    (BANNER_JUMP_TYPE_OTHER_APPLET, '第三方小程序')
)

BANNER_APPLET_TYPE_MERCHANT = 0
BANNER_APPLET_TYPE_CUSTOMER = 1
BANNER_APPLET_TYPE_CHOICE = Choices(
    (BANNER_APPLET_TYPE_MERCHANT, '商户小程序'),
    (BANNER_APPLET_TYPE_CUSTOMER, '消费者小程序')
)

ACTIVITY_STATUS_WAITING = 0
ACTIVITY_STATUS_ENABLE = 1
ACTIVITY_STATUS_DISABLE = 2
ACTIVITY_STATUS_CHOICE = Choices(
    (ACTIVITY_STATUS_WAITING, '等待开始'),
    (ACTIVITY_STATUS_ENABLE, '有效，进行中'),
    (ACTIVITY_STATUS_DISABLE, '禁用，已过期')
)

SHOP_INVITE_USER_TYPE_BOSS = 0
SHOP_INVITE_USER_TYPE_BARBER = 1
SHOP_INVITE_USER_TYPE_CUSTOMER = 2
SHOP_INVITE_USER_TYPE_CHOICE = Choices(
    (SHOP_INVITE_USER_TYPE_BOSS, '老板'),
    (SHOP_INVITE_USER_TYPE_BARBER, '理发师'),
    (SHOP_INVITE_USER_TYPE_CUSTOMER, '消费者')
)

SHOP_INVITE_STATUS_APPLIED = 0
SHOP_INVITE_STATUS_PASSED = 1
SHOP_INVITE_STATUS_REFUSE = 2
SHOP_INVITE_STATUS_FINISHED = 3
SHOP_INVITE_STATUS_CHOICE = Choices(
    (SHOP_INVITE_STATUS_APPLIED, '开店审核中'),
    (SHOP_INVITE_STATUS_PASSED, '红包已发放'),
    (SHOP_INVITE_STATUS_REFUSE, '开店未通过'),
    (SHOP_INVITE_STATUS_FINISHED, '活动完成')
)

SHOP_POSTER_APPLY_STATUS_APPLIED = 0
SHOP_POSTER_APPLY_STATUS_SEND = 1
SHOP_POSTER_APPLY_STATUS_REFUSE = 2
SHOP_POSTER_APPLY_STATUS_CHOICE = Choices(
    (SHOP_POSTER_APPLY_STATUS_APPLIED, '已申请'),
    (SHOP_POSTER_APPLY_STATUS_SEND, '已发送'),
    (SHOP_POSTER_APPLY_STATUS_REFUSE, '已拒绝')
)

COUPON_ACTIVITY_TYPE_CONSUME = 0
COUPON_ACTIVITY_TYPE_RECEIVE = 1
COUPON_ACTIVITY_TYPE_SHARE = 2
COUPON_ACTIVITY_TYPE_PIN = 3
COUPON_ACTIVITY_TYPE_CHOICE = Choices(
    (COUPON_ACTIVITY_TYPE_CONSUME, '消费返券'),
    (COUPON_ACTIVITY_TYPE_RECEIVE, '主动领券'),
    (COUPON_ACTIVITY_TYPE_SHARE, '分享领券'),
    (COUPON_ACTIVITY_TYPE_PIN, '拼团领券'),
)

PIN_STATUS_ING = 0
PIN_STATUS_SUCCESS = 1
PIN_STATUS_FAILED = 2
PIN_STATUS_CHOICE = Choices(
    (PIN_STATUS_ING, '拼团中'),
    (PIN_STATUS_SUCCESS, '拼团成功'),
    (PIN_STATUS_FAILED, '拼团失败')
)

PIN_AWARD_RULES_TYPE_MEMBER = 0
PIN_AWARD_RULES_TYPE_SPONSOR = 1
PIN_AWARD_RULES_TYPE_ALL = 2
PIN_AWARD_RULES_TYPE_CHOICE = Choices(
    (PIN_AWARD_RULES_TYPE_MEMBER, '限团员可领'),
    (PIN_AWARD_RULES_TYPE_SPONSOR, '限团长可领'),
    (PIN_AWARD_RULES_TYPE_ALL, '皆可领取')
)
